import type { DesignSystem } from '../types/designSystem.types'

export const DEFAULT_DESIGN_SYSTEM: DesignSystem = {
  id: 'ds-default',
  name: 'Astar Utbildning',
  version: '2.0',
  isActive: true,
  logoAssetUrl: '',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  colors: [
    { key: 'brand-primary', label: 'Primär blå', hex: '#0057A8', usageNotes: 'Knappar, länkar, accentelement' },
    { key: 'brand-secondary', label: 'Djup blå', hex: '#003F7F', usageNotes: 'Mörka bakgrunder, header' },
    { key: 'brand-accent', label: 'Guld/Orange', hex: '#E8A020', usageNotes: 'CTA, höjdpunkter' },
    { key: 'neutral-100', label: 'Vit', hex: '#FFFFFF' },
    { key: 'neutral-200', label: 'Ljusgrå', hex: '#F0F4F8' },
    { key: 'neutral-300', label: 'Gråblå', hex: '#D1DCE8' },
    { key: 'neutral-800', label: 'Mörkgrå', hex: '#2D3748' },
    { key: 'neutral-900', label: 'Nästan svart', hex: '#1A202C' },
    { key: 'surface-light', label: 'Ljus yta', hex: '#F8FAFC' },
    { key: 'surface-dark', label: 'Mörk yta', hex: '#0F1827' },
  ],
  typography: [
    {
      key: 'heading-xl',
      fontFamily: 'Inter',
      fontWeight: 700,
      sizeRem: 2.25,
      lineHeight: 1.15,
      letterSpacing: '-0.02em',
      colorTokenKey: 'neutral-100',
      textTransform: 'none',
    },
    {
      key: 'heading-lg',
      fontFamily: 'Inter',
      fontWeight: 700,
      sizeRem: 1.75,
      lineHeight: 1.2,
      letterSpacing: '-0.01em',
      colorTokenKey: 'neutral-900',
    },
    {
      key: 'subheading-md',
      fontFamily: 'Inter',
      fontWeight: 500,
      sizeRem: 1.125,
      lineHeight: 1.4,
      colorTokenKey: 'neutral-200',
    },
    {
      key: 'body-base',
      fontFamily: 'Inter',
      fontWeight: 400,
      sizeRem: 0.9375,
      lineHeight: 1.6,
      colorTokenKey: 'neutral-900',
    },
    {
      key: 'body-sm',
      fontFamily: 'Inter',
      fontWeight: 400,
      sizeRem: 0.8125,
      lineHeight: 1.5,
      colorTokenKey: 'neutral-800',
    },
    {
      key: 'cta',
      fontFamily: 'Inter',
      fontWeight: 600,
      sizeRem: 0.9375,
      lineHeight: 1,
      letterSpacing: '0.02em',
      colorTokenKey: 'neutral-100',
      textTransform: 'uppercase',
    },
  ],
  spacing: [
    { key: 'space-xs', valueRem: 0.25 },
    { key: 'space-sm', valueRem: 0.5 },
    { key: 'space-md', valueRem: 1 },
    { key: 'space-lg', valueRem: 1.5 },
    { key: 'space-xl', valueRem: 2 },
    { key: 'space-2xl', valueRem: 3 },
  ],
  logoRules: {
    minWidthPx: 80,
    clearspaceMultiplier: 0.25,
    allowedVariants: ['full-color', 'white', 'black'],
    allowedPlacements: ['top-left', 'top-right', 'bottom-left', 'bottom-right'],
  },
}
