import type { TemplateDefinition } from '../types/template.types'

export const BUILT_IN_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'tmpl-course-portrait',
    name: 'Kursblad – Stående',
    description: 'Ensidigt A4-kursblad med gradienthero och strukturerat innehåll',
    thumbnailUrl: '',
    category: 'course',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'portrait',
        backgroundGradientId: 'grad-brand-diagonal',
        slots: [
          {
            id: 'slot-logo',
            type: 'logo',
            label: 'Logotyp',
            zIndex: 10,
            visible: true,
            position: { x: 12, y: 10, width: 45, height: 15 },
            constraints: { logoVariant: 'white', required: true },
          },
          {
            id: 'slot-heading',
            type: 'heading',
            label: 'Kurstitel',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 40, width: 186, height: 30 },
            constraints: {
              typographyTokenKey: 'heading-xl',
              colorTokenKey: 'neutral-100',
              maxChars: 80,
              required: true,
            },
            aiPromptHint: 'Skriv en engagerande kurstitel. Max 10 ord. Använd satsfall.',
          },
          {
            id: 'slot-subheading',
            type: 'subheading',
            label: 'Underrubrik / Ingress',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 75, width: 140, height: 20 },
            constraints: {
              typographyTokenKey: 'subheading-md',
              colorTokenKey: 'neutral-200',
              maxChars: 160,
            },
            aiPromptHint: 'Skriv en 1–2 meningar lång ingress. Engagerande och informativ.',
          },
          {
            id: 'slot-hero-image',
            type: 'image',
            label: 'Herобild',
            zIndex: 1,
            visible: true,
            position: { x: 0, y: 100, width: 210, height: 80 },
            constraints: { imageAspectRatio: 2.625 },
          },
          {
            id: 'slot-description',
            type: 'body-text',
            label: 'Kursbeskrivning',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 195, width: 118, height: 65 },
            constraints: {
              typographyTokenKey: 'body-base',
              colorTokenKey: 'neutral-900',
              maxChars: 600,
            },
            aiPromptHint: 'Skriv en 3–4 meningar lång kursbeskrivning. Professionell och motiverande.',
          },
          {
            id: 'slot-bullets',
            type: 'bullet-list',
            label: 'Du lär dig',
            zIndex: 5,
            visible: true,
            position: { x: 142, y: 195, width: 56, height: 65 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxBullets: 6,
            },
            aiPromptHint: 'Lista 4–6 lärandemål. Börja varje med ett verb. Kort och kärnfullt.',
          },
          {
            id: 'slot-cta',
            type: 'cta',
            label: 'CTA-knapp',
            zIndex: 6,
            visible: true,
            position: { x: 12, y: 272, width: 70, height: 12 },
            constraints: {
              typographyTokenKey: 'cta',
              colorTokenKey: 'brand-primary',
              maxChars: 30,
            },
            aiPromptHint: 'Skriv en kort handlingsorienterad CTA. 2–5 ord.',
          },
          {
            id: 'slot-contact',
            type: 'contact',
            label: 'Kontaktperson',
            zIndex: 5,
            visible: true,
            position: { x: 130, y: 268, width: 68, height: 22 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-800',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-product-landscape',
    name: 'Produktblad – Liggande',
    description: 'Tvåkolumns A4-produktblad i liggande format',
    thumbnailUrl: '',
    category: 'product',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'landscape',
        backgroundGradientId: 'grad-light-subtle',
        slots: [
          {
            id: 'slot-logo-ls',
            type: 'logo',
            label: 'Logotyp',
            zIndex: 10,
            visible: true,
            position: { x: 10, y: 8, width: 40, height: 13 },
            constraints: { logoVariant: 'full-color', required: true },
          },
          {
            id: 'slot-heading-ls',
            type: 'heading',
            label: 'Produkttitel',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 35, width: 130, height: 25 },
            constraints: {
              typographyTokenKey: 'heading-lg',
              colorTokenKey: 'neutral-900',
              maxChars: 60,
              required: true,
            },
            aiPromptHint: 'Skriv en tydlig och säljande produkttitel.',
          },
          {
            id: 'slot-subheading-ls',
            type: 'subheading',
            label: 'Underrubrik',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 63, width: 130, height: 15 },
            constraints: {
              typographyTokenKey: 'subheading-md',
              colorTokenKey: 'brand-primary',
              maxChars: 120,
            },
            aiPromptHint: 'Skriv en kort underrubrik som kompletterar produkttiteln.',
          },
          {
            id: 'slot-body-ls',
            type: 'body-text',
            label: 'Produktbeskrivning',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 82, width: 130, height: 80 },
            constraints: {
              typographyTokenKey: 'body-base',
              colorTokenKey: 'neutral-900',
              maxChars: 700,
            },
            aiPromptHint: 'Skriv en övertygande produktbeskrivning. Fokusera på nytta och värde.',
          },
          {
            id: 'slot-image-ls',
            type: 'image',
            label: 'Produktbild',
            zIndex: 3,
            visible: true,
            position: { x: 155, y: 8, width: 132, height: 154 },
            constraints: { imageAspectRatio: 0.857 },
          },
          {
            id: 'slot-bullets-ls',
            type: 'bullet-list',
            label: 'Fördelar',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 168, width: 130, height: 25 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-800',
              maxBullets: 5,
            },
            aiPromptHint: 'Lista 3–5 produktfördelar. Koncisa och faktabaserade.',
          },
          {
            id: 'slot-cta-ls',
            type: 'cta',
            label: 'CTA',
            zIndex: 6,
            visible: true,
            position: { x: 10, y: 196, width: 65, height: 10 },
            constraints: {
              typographyTokenKey: 'cta',
              colorTokenKey: 'brand-primary',
              maxChars: 25,
            },
            aiPromptHint: 'Skriv en CTA på 2–4 ord.',
          },
          {
            id: 'slot-contact-ls',
            type: 'contact',
            label: 'Kontakt',
            zIndex: 5,
            visible: true,
            position: { x: 155, y: 168, width: 132, height: 38 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-800',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-event-portrait',
    name: 'Eventblad – Stående',
    description: 'Dramatiskt eventblad med stor bild och minimalt innehåll',
    thumbnailUrl: '',
    category: 'event',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'portrait',
        backgroundGradientId: 'grad-dark-radial',
        slots: [
          {
            id: 'slot-logo-ev',
            type: 'logo',
            label: 'Logotyp',
            zIndex: 10,
            visible: true,
            position: { x: 12, y: 10, width: 40, height: 13 },
            constraints: { logoVariant: 'white', required: true },
          },
          {
            id: 'slot-event-image',
            type: 'image',
            label: 'Eventbild',
            zIndex: 1,
            visible: true,
            position: { x: 0, y: 0, width: 210, height: 150 },
            constraints: { imageAspectRatio: 1.4 },
          },
          {
            id: 'slot-event-heading',
            type: 'heading',
            label: 'Eventtitel',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 155, width: 186, height: 35 },
            constraints: {
              typographyTokenKey: 'heading-xl',
              colorTokenKey: 'neutral-100',
              maxChars: 60,
              required: true,
            },
            aiPromptHint: 'Skriv en kraftfull eventtitel som skapar nyfikenhet.',
          },
          {
            id: 'slot-event-desc',
            type: 'body-text',
            label: 'Eventbeskrivning',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 198, width: 186, height: 60 },
            constraints: {
              typographyTokenKey: 'body-base',
              colorTokenKey: 'neutral-200',
              maxChars: 400,
            },
            aiPromptHint: 'Beskriv eventet kortfattat. Vad, när, varför delta.',
          },
          {
            id: 'slot-event-cta',
            type: 'cta',
            label: 'CTA',
            zIndex: 6,
            visible: true,
            position: { x: 12, y: 268, width: 80, height: 12 },
            constraints: {
              typographyTokenKey: 'cta',
              colorTokenKey: 'brand-accent',
              maxChars: 30,
            },
            aiPromptHint: 'Skriv en CTA för eventanmälan.',
          },
        ],
      },
    ],
  },
]
