import type { TemplateDefinition } from '../types/template.types'

export const BUILT_IN_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'tmpl-course-portrait',
    name: 'Kursblad – Stående',
    description: 'Ensidigt A4-kursblad med gradienthero och strukturerat innehåll',
    thumbnailUrl: '',
    category: 'course',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'portrait',
        backgroundGradientId: 'grad-brand-diagonal',
        slots: [
          {
            id: 'slot-logo',
            type: 'logo',
            label: 'Logotyp',
            zIndex: 10,
            visible: true,
            position: { x: 12, y: 10, width: 45, height: 15 },
            constraints: { logoVariant: 'white', required: true },
          },
          {
            id: 'slot-heading',
            type: 'heading',
            label: 'Kurstitel',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 40, width: 186, height: 30 },
            constraints: {
              typographyTokenKey: 'heading-xl',
              colorTokenKey: 'neutral-100',
              maxChars: 80,
              required: true,
            },
            aiPromptHint: 'Skriv en engagerande kurstitel. Max 10 ord. Använd satsfall.',
          },
          {
            id: 'slot-subheading',
            type: 'subheading',
            label: 'Underrubrik / Ingress',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 75, width: 140, height: 20 },
            constraints: {
              typographyTokenKey: 'subheading-md',
              colorTokenKey: 'neutral-200',
              maxChars: 160,
            },
            aiPromptHint: 'Skriv en 1–2 meningar lång ingress. Engagerande och informativ.',
          },
          {
            id: 'slot-hero-image',
            type: 'image',
            label: 'Herобild',
            zIndex: 1,
            visible: true,
            position: { x: 0, y: 100, width: 210, height: 80 },
            constraints: { imageAspectRatio: 2.625 },
          },
          {
            id: 'slot-description',
            type: 'body-text',
            label: 'Kursbeskrivning',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 195, width: 118, height: 65 },
            constraints: {
              typographyTokenKey: 'body-base',
              colorTokenKey: 'neutral-900',
              maxChars: 600,
            },
            aiPromptHint: 'Skriv en 3–4 meningar lång kursbeskrivning. Professionell och motiverande.',
          },
          {
            id: 'slot-bullets',
            type: 'bullet-list',
            label: 'Du lär dig',
            zIndex: 5,
            visible: true,
            position: { x: 142, y: 195, width: 56, height: 65 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxBullets: 6,
            },
            aiPromptHint: 'Lista 4–6 lärandemål. Börja varje med ett verb. Kort och kärnfullt.',
          },
          {
            id: 'slot-cta',
            type: 'cta',
            label: 'CTA-knapp',
            zIndex: 6,
            visible: true,
            position: { x: 12, y: 272, width: 70, height: 12 },
            constraints: {
              typographyTokenKey: 'cta',
              colorTokenKey: 'brand-primary',
              maxChars: 30,
            },
            aiPromptHint: 'Skriv en kort handlingsorienterad CTA. 2–5 ord.',
          },
          {
            id: 'slot-contact',
            type: 'contact',
            label: 'Kontaktperson',
            zIndex: 5,
            visible: true,
            position: { x: 130, y: 268, width: 68, height: 22 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-800',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-product-landscape',
    name: 'Produktblad – Liggande',
    description: 'Tvåkolumns A4-produktblad i liggande format',
    thumbnailUrl: '',
    category: 'product',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'landscape',
        backgroundGradientId: 'grad-light-subtle',
        slots: [
          {
            id: 'slot-logo-ls',
            type: 'logo',
            label: 'Logotyp',
            zIndex: 10,
            visible: true,
            position: { x: 10, y: 8, width: 40, height: 13 },
            constraints: { logoVariant: 'full-color', required: true },
          },
          {
            id: 'slot-heading-ls',
            type: 'heading',
            label: 'Produkttitel',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 35, width: 130, height: 25 },
            constraints: {
              typographyTokenKey: 'heading-lg',
              colorTokenKey: 'neutral-900',
              maxChars: 60,
              required: true,
            },
            aiPromptHint: 'Skriv en tydlig och säljande produkttitel.',
          },
          {
            id: 'slot-subheading-ls',
            type: 'subheading',
            label: 'Underrubrik',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 63, width: 130, height: 15 },
            constraints: {
              typographyTokenKey: 'subheading-md',
              colorTokenKey: 'brand-primary',
              maxChars: 120,
            },
            aiPromptHint: 'Skriv en kort underrubrik som kompletterar produkttiteln.',
          },
          {
            id: 'slot-body-ls',
            type: 'body-text',
            label: 'Produktbeskrivning',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 82, width: 130, height: 80 },
            constraints: {
              typographyTokenKey: 'body-base',
              colorTokenKey: 'neutral-900',
              maxChars: 700,
            },
            aiPromptHint: 'Skriv en övertygande produktbeskrivning. Fokusera på nytta och värde.',
          },
          {
            id: 'slot-image-ls',
            type: 'image',
            label: 'Produktbild',
            zIndex: 3,
            visible: true,
            position: { x: 155, y: 8, width: 132, height: 154 },
            constraints: { imageAspectRatio: 0.857 },
          },
          {
            id: 'slot-bullets-ls',
            type: 'bullet-list',
            label: 'Fördelar',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 168, width: 130, height: 25 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-800',
              maxBullets: 5,
            },
            aiPromptHint: 'Lista 3–5 produktfördelar. Koncisa och faktabaserade.',
          },
          {
            id: 'slot-cta-ls',
            type: 'cta',
            label: 'CTA',
            zIndex: 6,
            visible: true,
            position: { x: 10, y: 196, width: 65, height: 10 },
            constraints: {
              typographyTokenKey: 'cta',
              colorTokenKey: 'brand-primary',
              maxChars: 25,
            },
            aiPromptHint: 'Skriv en CTA på 2–4 ord.',
          },
          {
            id: 'slot-contact-ls',
            type: 'contact',
            label: 'Kontakt',
            zIndex: 5,
            visible: true,
            position: { x: 155, y: 168, width: 132, height: 38 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-800',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-event-portrait',
    name: 'Eventblad – Stående',
    description: 'Dramatiskt eventblad med stor bild och minimalt innehåll',
    thumbnailUrl: '',
    category: 'event',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'portrait',
        backgroundGradientId: 'grad-dark-radial',
        slots: [
          {
            id: 'slot-logo-ev',
            type: 'logo',
            label: 'Logotyp',
            zIndex: 10,
            visible: true,
            position: { x: 12, y: 10, width: 40, height: 13 },
            constraints: { logoVariant: 'white', required: true },
          },
          {
            id: 'slot-event-image',
            type: 'image',
            label: 'Eventbild',
            zIndex: 1,
            visible: true,
            position: { x: 0, y: 0, width: 210, height: 150 },
            constraints: { imageAspectRatio: 1.4 },
          },
          {
            id: 'slot-event-heading',
            type: 'heading',
            label: 'Eventtitel',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 155, width: 186, height: 35 },
            constraints: {
              typographyTokenKey: 'heading-xl',
              colorTokenKey: 'neutral-100',
              maxChars: 60,
              required: true,
            },
            aiPromptHint: 'Skriv en kraftfull eventtitel som skapar nyfikenhet.',
          },
          {
            id: 'slot-event-desc',
            type: 'body-text',
            label: 'Eventbeskrivning',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 198, width: 186, height: 60 },
            constraints: {
              typographyTokenKey: 'body-base',
              colorTokenKey: 'neutral-200',
              maxChars: 400,
            },
            aiPromptHint: 'Beskriv eventet kortfattat. Vad, när, varför delta.',
          },
          {
            id: 'slot-event-cta',
            type: 'cta',
            label: 'CTA',
            zIndex: 6,
            visible: true,
            position: { x: 12, y: 268, width: 80, height: 12 },
            constraints: {
              typographyTokenKey: 'cta',
              colorTokenKey: 'brand-accent',
              maxChars: 30,
            },
            aiPromptHint: 'Skriv en CTA för eventanmälan.',
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-byggnadsmalare-bromma',
    name: 'Arbetsmarknadsutbildning – Bromma',
    description: 'Tvåkolumns A4-produktblad för arbetsmarknadsutbildningar i samarbete med Arbetsförmedlingen',
    thumbnailUrl: '',
    category: 'course',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'portrait',
        backgroundColorTokenKey: 'neutral-100',
        slots: [
          // ── HEADER BANNER ──────────────────────────────────────────
          {
            id: 'slot-header-bg',
            type: 'gradient-background',
            label: 'Headerbakgrund',
            zIndex: 1,
            visible: true,
            position: { x: 0, y: 0, width: 210, height: 18 },
            constraints: { gradientId: 'grad-navy-solid' },
          },
          {
            id: 'slot-header-label',
            type: 'heading',
            label: 'Etikett (header)',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 4, width: 186, height: 10 },
            constraints: {
              typographyTokenKey: 'label-xs',
              colorTokenKey: 'neutral-100',
              maxChars: 80,
              required: true,
            },
            aiPromptHint: 'Skriv en kort säljande etikett i versaler, max 10 ord. t.ex. "PRAKTISK UTBILDNING MED STORA MÖJLIGHETER TILL JOBB"',
          },

          // ── HERO ────────────────────────────────────────────────────
          {
            id: 'slot-hero-heading',
            type: 'heading',
            label: 'Herorubruk',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 22, width: 114, height: 34 },
            constraints: {
              typographyTokenKey: 'heading-hero',
              colorTokenKey: 'brand-secondary',
              maxChars: 70,
              required: true,
            },
            aiPromptHint: 'Skriv en stor inspirerande rubrik för utbildningen. Max 8 ord. Exempel: "Bygg din framtid som byggnadsmålare"',
          },
          {
            id: 'slot-hero-subheading',
            type: 'subheading',
            label: 'Ingress',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 58, width: 114, height: 20 },
            constraints: {
              typographyTokenKey: 'subheading-dark',
              colorTokenKey: 'neutral-900',
              maxChars: 160,
            },
            aiPromptHint: 'Skriv en 1–2 meningar lång ingress som lockar till utbildningen.',
          },
          {
            id: 'slot-hero-image',
            type: 'image',
            label: 'Herobilder',
            zIndex: 3,
            visible: true,
            position: { x: 128, y: 18, width: 82, height: 64 },
            constraints: { imageAspectRatio: 1.28 },
          },

          // ── VÄNSTERKOLUMN ───────────────────────────────────────────
          {
            id: 'slot-varfor-heading',
            type: 'heading',
            label: 'Rubrik: Varför detta yrke?',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 90, width: 91, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 50,
            },
            aiPromptHint: 'Skriv en kort sektionsrubrik om varför man ska välja detta yrke. t.ex. "Varför bli byggnadsmålare?"',
          },
          {
            id: 'slot-varfor-body',
            type: 'body-text',
            label: 'Brödtext: Varför detta yrke?',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 98, width: 91, height: 36 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 450,
            },
            aiPromptHint: 'Beskriv varför yrket är attraktivt. Kreativt, praktiskt, god efterfrågan. 3–4 meningar.',
          },
          {
            id: 'slot-lar-heading',
            type: 'heading',
            label: 'Rubrik: Det här lär du dig',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 137, width: 91, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 50,
            },
            aiPromptHint: 'Skriv en sektionsrubrik om utbildningsinnehållet. t.ex. "Det här lär du dig"',
          },
          {
            id: 'slot-lar-body',
            type: 'body-text',
            label: 'Brödtext: Utbildningsinnehåll',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 145, width: 91, height: 38 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 500,
            },
            aiPromptHint: 'Beskriv vad deltagaren lär sig: praktiska moment, teori, APL, verktyg. 3–4 meningar.',
          },
          {
            id: 'slot-gar-heading',
            type: 'heading',
            label: 'Rubrik: Så här går det till',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 186, width: 91, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 50,
            },
            aiPromptHint: 'Skriv en sektionsrubrik om hur utbildningen är upplagd. t.ex. "Så här går det till"',
          },
          {
            id: 'slot-gar-body',
            type: 'body-text',
            label: 'Brödtext: Genomförande',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 194, width: 91, height: 30 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 400,
            },
            aiPromptHint: 'Beskriv utbildningens upplägg: introduktion, teori + praktik, APL, branschsamarbete.',
          },

          // ── HÖGERKOLUMN ─────────────────────────────────────────────
          {
            id: 'slot-vem-heading',
            type: 'heading',
            label: 'Rubrik: Vem kan söka?',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 90, width: 89, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 50,
            },
            aiPromptHint: 'Skriv en sektionsrubrik om behörighet. t.ex. "Vem kan söka?"',
          },
          {
            id: 'slot-vem-body',
            type: 'body-text',
            label: 'Brödtext: Vem kan söka?',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 98, width: 89, height: 24 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 300,
            },
            aiPromptHint: 'Beskriv vem som kan söka via Arbetsförmedlingen. Kort och tydligt, 2 meningar.',
          },
          {
            id: 'slot-far-heading',
            type: 'heading',
            label: 'Rubrik: Det här får du på Astar',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 125, width: 89, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 50,
            },
            aiPromptHint: 'Skriv en sektionsrubrik om fördelar med Astar. t.ex. "Det här får du på Astar"',
          },
          {
            id: 'slot-far-bullets',
            type: 'bullet-list',
            label: 'Fördelar med Astar',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 133, width: 89, height: 22 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxBullets: 4,
            },
            aiPromptHint: 'Lista 3–4 konkreta fördelar med att utbilda sig på Astar. Börja varje punkt med versal.',
          },
          {
            id: 'slot-start-heading',
            type: 'heading',
            label: 'Rubrik: Utbildningsstart',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 158, width: 89, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 40,
            },
            aiPromptHint: 'Skriv sektionsrubrik "Utbildningsstart"',
          },
          {
            id: 'slot-start-body',
            type: 'body-text',
            label: 'Text: Utbildningsstart',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 166, width: 89, height: 10 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 120,
            },
            aiPromptHint: 'Kort text om när utbildningen startar, hänvisa till Arbetsförmedlingens handläggare.',
          },
          {
            id: 'slot-ersattning-heading',
            type: 'heading',
            label: 'Rubrik: Ekonomisk kompensation',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 179, width: 89, height: 7 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 45,
            },
            aiPromptHint: 'Skriv sektionsrubrik "Ekonomisk kompensation"',
          },
          {
            id: 'slot-ersattning-body',
            type: 'body-text',
            label: 'Text: Ekonomisk kompensation',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 187, width: 89, height: 12 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 150,
            },
            aiPromptHint: 'Förklara att man ansöker om aktivitetsstöd/etableringsersättning via Arbetsförmedlingen.',
          },
          {
            id: 'slot-contact',
            type: 'contact',
            label: 'Kontaktperson',
            zIndex: 5,
            visible: true,
            position: { x: 109, y: 202, width: 89, height: 22 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'brand-secondary',
            },
          },

          // ── FOOTER ──────────────────────────────────────────────────
          {
            id: 'slot-footer-bg',
            type: 'gradient-background',
            label: 'Footerbakgrund',
            zIndex: 1,
            visible: true,
            position: { x: 0, y: 228, width: 210, height: 69 },
            constraints: { gradientId: 'grad-white-solid' },
          },
          {
            id: 'slot-footer-body',
            type: 'body-text',
            label: 'Brödtext: Om Astar (footer)',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 232, width: 186, height: 18 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-900',
              maxChars: 350,
            },
            aiPromptHint: 'Skriv en kort beskrivning av Astar som utbildningsföretag. Ca 2–3 meningar.',
          },
          {
            id: 'slot-footer-logo',
            type: 'logo',
            label: 'Astar-logotyp',
            zIndex: 5,
            visible: true,
            position: { x: 12, y: 254, width: 38, height: 12 },
            constraints: { logoVariant: 'full-color' },
          },
          {
            id: 'slot-footer-address',
            type: 'body-text',
            label: 'Adress',
            zIndex: 5,
            visible: true,
            position: { x: 56, y: 256, width: 90, height: 8 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-800',
              maxChars: 80,
            },
            aiPromptHint: 'Adress till aktuellt Astar-kontor.',
          },
          {
            id: 'slot-footer-partner',
            type: 'body-text',
            label: 'Samarbetspartner (footer)',
            zIndex: 5,
            visible: true,
            position: { x: 148, y: 254, width: 50, height: 12 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-800',
              maxChars: 60,
            },
            aiPromptHint: 'Skriv "I samarbete med: Arbetsförmedlingen"',
          },
        ],
      },
    ],
  },

  // ────────────────────────────────────────────────────────────────────────────
  // KOMVUX NORRKÖPING – Bagare/Konditor kombinationsflyer
  // Layout: Hero (left dark panel + right image) + 2-col body + footer
  // ────────────────────────────────────────────────────────────────────────────
  {
    id: 'tmpl-komvux-norrköping',
    name: 'KOMVUX Norrköping – Kombokurs',
    description: 'Kombinationsflyer för KOMVUX-kurser med Lora-rubriker och tvåkolumns innehåll',
    thumbnailUrl: '',
    category: 'komvux',
    designSystemId: 'ds-default',
    isPublished: true,
    createdBy: 'system',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    pages: [
      {
        pageNumber: 1,
        orientation: 'portrait',
        slots: [
          // ── HERO: LEFT DARK PANEL (locked pattern background) ──────────────
          {
            id: 'knk-hero-bg-left',
            type: 'gradient-background',
            label: 'Hero vänster bakgrund (låst)',
            zIndex: 1,
            visible: true,
            locked: true,
            position: { x: 0, y: 0, width: 120, height: 100 },
            constraints: { gradientId: 'grad-brand-vertical' },
          },
          // ── HERO: KOMVUX BADGE ──────────────────────────────────────────────
          {
            id: 'knk-komvux-badge',
            type: 'heading',
            label: 'KOMVUX-badge',
            zIndex: 10,
            visible: true,
            position: { x: 8, y: 8, width: 50, height: 9 },
            constraints: {
              typographyTokenKey: 'label-xs',
              colorTokenKey: 'neutral-100',
              maxChars: 20,
              required: true,
            },
            aiPromptHint: 'Skriv "KOMVUX" i versaler.',
          },
          // ── HERO: MAIN HEADING (Lora serif) ────────────────────────────────
          {
            id: 'knk-hero-heading',
            type: 'heading',
            label: 'Kursnamn (hero-rubrik)',
            zIndex: 10,
            visible: true,
            position: { x: 8, y: 25, width: 104, height: 45 },
            constraints: {
              typographyTokenKey: 'heading-lora-hero',
              colorTokenKey: 'neutral-100',
              maxChars: 60,
              required: true,
            },
            aiPromptHint: 'Skriv kursnamnet med Lora-serif. Kan vara flerrads. Max 5 ord.',
          },
          // ── HERO: SUBHEADING ────────────────────────────────────────────────
          {
            id: 'knk-hero-subheading',
            type: 'subheading',
            label: 'Hero underrubrik',
            zIndex: 10,
            visible: true,
            position: { x: 8, y: 73, width: 104, height: 12 },
            constraints: {
              typographyTokenKey: 'subheading-md',
              colorTokenKey: 'neutral-200',
              maxChars: 80,
            },
            aiPromptHint: 'En kort beskrivande mening om kursen. Max 12 ord.',
          },
          // ── HERO: RIGHT IMAGE ───────────────────────────────────────────────
          {
            id: 'knk-hero-image',
            type: 'image',
            label: 'Hero-bild (höger)',
            zIndex: 5,
            visible: true,
            position: { x: 120, y: 0, width: 90, height: 100 },
            constraints: {
              imageAspectRatio: 1.0,
              required: true,
            },
            aiPromptHint: 'Välj en inspirerande bild som representerar kursen.',
          },
          // ── LOGO (top-right) ────────────────────────────────────────────────
          {
            id: 'knk-logo',
            type: 'logo',
            label: 'Astar-logotyp',
            zIndex: 15,
            visible: true,
            position: { x: 168, y: 6, width: 34, height: 11 },
            constraints: { logoVariant: 'white' },
          },

          // ── BODY: LEFT COLUMN ───────────────────────────────────────────────
          {
            id: 'knk-body-bg',
            type: 'gradient-background',
            label: 'Innehållsbakgrund (låst)',
            zIndex: 1,
            visible: true,
            locked: true,
            position: { x: 0, y: 100, width: 210, height: 145 },
            constraints: { gradientId: 'grad-white-solid' },
          },
          {
            id: 'knk-col1-heading1',
            type: 'heading',
            label: 'Rubrik 1 (vänster)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 108, width: 88, height: 9 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 40,
            },
            aiPromptHint: 'Kort avsnittshuvud, t.ex. "Vad lär du dig?" eller "Om kursen". Max 5 ord.',
          },
          {
            id: 'knk-col1-body1',
            type: 'body-text',
            label: 'Brödtext 1 (vänster)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 118, width: 88, height: 30 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxChars: 300,
            },
            aiPromptHint: 'Beskriv vad kursen handlar om och vad eleven lär sig. 3–5 meningar.',
          },
          {
            id: 'knk-col1-heading2',
            type: 'heading',
            label: 'Rubrik 2 (vänster)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 152, width: 88, height: 9 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 40,
            },
            aiPromptHint: 'Kort avsnittshuvud, t.ex. "Krav och antagning". Max 5 ord.',
          },
          {
            id: 'knk-col1-body2',
            type: 'body-text',
            label: 'Brödtext 2 (vänster)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 162, width: 88, height: 22 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxChars: 200,
            },
            aiPromptHint: 'Ange förkunskapskrav och hur man ansöker. 2–3 meningar.',
          },
          {
            id: 'knk-col1-heading3',
            type: 'heading',
            label: 'Rubrik 3 (vänster)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 187, width: 88, height: 9 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 40,
            },
            aiPromptHint: 'Kort avsnittshuvud, t.ex. "Studieform". Max 5 ord.',
          },
          {
            id: 'knk-col1-body3',
            type: 'body-text',
            label: 'Brödtext 3 (vänster)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 197, width: 88, height: 18 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxChars: 200,
            },
            aiPromptHint: 'Beskriv studieform, studietakt och eventuell praktik.',
          },

          // ── BODY: RIGHT COLUMN ──────────────────────────────────────────────
          {
            id: 'knk-col2-heading1',
            type: 'heading',
            label: 'Rubrik 1 (höger)',
            zIndex: 5,
            visible: true,
            position: { x: 112, y: 108, width: 88, height: 9 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 40,
            },
            aiPromptHint: 'Kort avsnittshuvud, t.ex. "Kursens upplägg". Max 5 ord.',
          },
          {
            id: 'knk-col2-body1',
            type: 'body-text',
            label: 'Brödtext 1 (höger)',
            zIndex: 5,
            visible: true,
            position: { x: 112, y: 118, width: 88, height: 30 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxChars: 300,
            },
            aiPromptHint: 'Beskriv hur kursen är upplagd, block, moment etc. 3–5 meningar.',
          },
          {
            id: 'knk-col2-heading2',
            type: 'heading',
            label: 'Rubrik 2 (höger)',
            zIndex: 5,
            visible: true,
            position: { x: 112, y: 152, width: 88, height: 9 },
            constraints: {
              typographyTokenKey: 'section-heading',
              colorTokenKey: 'brand-secondary',
              maxChars: 40,
            },
            aiPromptHint: 'Kort avsnittshuvud, t.ex. "Ekonomiskt stöd". Max 5 ord.',
          },
          {
            id: 'knk-col2-body2',
            type: 'body-text',
            label: 'Brödtext 2 (höger)',
            zIndex: 5,
            visible: true,
            position: { x: 112, y: 162, width: 88, height: 22 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'neutral-900',
              maxChars: 200,
            },
            aiPromptHint: 'Förklara om studiebidrag, aktivitetsstöd, CSN etc. 2–3 meningar.',
          },
          {
            id: 'knk-contact',
            type: 'contact',
            label: 'Kontaktperson',
            zIndex: 5,
            visible: true,
            position: { x: 112, y: 188, width: 88, height: 24 },
            constraints: {
              typographyTokenKey: 'body-sm',
              colorTokenKey: 'brand-secondary',
            },
          },

          // ── FOOTER ──────────────────────────────────────────────────────────
          {
            id: 'knk-footer-bg',
            type: 'gradient-background',
            label: 'Footerbakgrund (låst)',
            zIndex: 1,
            visible: true,
            locked: true,
            position: { x: 0, y: 245, width: 210, height: 52 },
            constraints: { gradientId: 'grad-navy-solid' },
          },
          {
            id: 'knk-footer-body',
            type: 'body-text',
            label: 'Om Astar (footer)',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 250, width: 130, height: 22 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-200',
              maxChars: 350,
            },
            aiPromptHint: 'Kort om Astar Utbildning – vad vi erbjuder och var vi finns. 2–3 meningar.',
          },
          {
            id: 'knk-footer-logo',
            type: 'logo',
            label: 'Astar-logotyp (footer)',
            zIndex: 5,
            visible: true,
            position: { x: 78, y: 274, width: 54, height: 16 },
            constraints: { logoVariant: 'white' },
          },
          {
            id: 'knk-footer-address',
            type: 'body-text',
            label: 'Adress',
            zIndex: 5,
            visible: true,
            position: { x: 10, y: 275, width: 68, height: 14 },
            constraints: {
              typographyTokenKey: 'body-xs',
              colorTokenKey: 'neutral-300',
              maxChars: 100,
            },
            aiPromptHint: 'Skriv adressen till Astar Norrköping.',
          },
          {
            id: 'knk-footer-qr',
            type: 'image',
            label: 'QR-kod',
            zIndex: 5,
            visible: true,
            position: { x: 180, y: 250, width: 22, height: 22 },
            constraints: {
              imageAspectRatio: 1,
            },
            aiPromptHint: 'QR-kod som leder till kursens webbsida.',
          },
        ],
      },
    ],
  },
]
